version: "3.1"

services:
  app:
    image: sommerlan-app:${BRANCH}-${SHA}
    restart: unless-stopped
    environment:
      SESSION_SECRET: sommerlan-rocks-cookies
      APPLICATION_SERVER_KEY: "${VAPID_PUBLIC_KEY}"
      APPLICATION_SERVER_PRIVATE_KEY: "${VAPID_PRIVATE_KEY}"
      APP_ORIGIN: "${APP_ORIGIN}"
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
      GOOGLE_SHEET_ID: "${GOOGLE_SHEET_ID}"
      GOOGLE_SERVICE_ACCOUNT_EMAIL: "${GOOGLE_SERVICE_ACCOUNT_EMAIL}"
      GOOGLE_PRIVATE_KEY: "${GOOGLE_PRIVATE_KEY}"
    ports:
      - "${APP_PORT}:8080"
