version: "3.1"

services:
  app:
    image: sommerlan-app:${BRANCH}-${SHA}
    restart: unless-stopped
    environment:
      SESSION_SECRET: sommerlan-rocks-cookies
      APPLICATION_SERVER_KEY: "${VAPID_PUBLIC_KEY}"
      APPLICATION_SERVER_PRIVATE_KEY: "${VAPID_PRIVATE_KEY}"
      APP_ORIGIN: "${APP_ORIGIN}"
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
      GOOGLE_SHEET_ID: "${GOOGLE_SHEET_ID}"
      GOOGLE_SERVICE_ACCOUNT_EMAIL: "${GOOGLE_SERVICE_ACCOUNT_EMAIL}"
      GOOGLE_PRIVATE_KEY: "${GOOGLE_PRIVATE_KEY}"
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "${NEW_RELIC_APP_NAME}"
      NEW_RELIC_LOADER_CONFIG: "${NEW_RELIC_LOADER_CONFIG}"
      NEW_RELIC_INFO: "${NEW_RELIC_INFO}"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      DISCORD_GUILD_ID: "${DISCORD_GUILD_ID}"
      DISCORD_ROLE_ID: "${DISCORD_ROLE_ID}"
    ports:
      - "${APP_PORT}:8080"
    networks:
      - default
      - mail
    volumes:
      - type: volume
        source: uploads
        target: /myapp/dist/client/uploads
        volume:
          nocopy: true

networks:
  default:
  mail:
    name: mailserver
    external: true

volumes:
  uploads:
