version: "3.1"

services:
  app:
    image: sommerlan-app:${BRANCH}-${SHA}
    restart: unless-stopped
    environment:
      SESSION_SECRET: sommerlan-rocks-cookies
      APPLICATION_SERVER_KEY: "${VAPID_PUBLIC_KEY}"
      APPLICATION_SERVER_PRIVATE_KEY: "${VAPID_PRIVATE_KEY}"
      GCM_KEY: "${GCM_KEY}"
    ports:
      - "${APP_PORT}:8080"
