name: ðŸ› Bug Report
description: Something is wrong with the Stack.
body:
  - type: markdown
    attributes:
      value: >-
        Thank you for helping to improve the sommerlan website!

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
