-- AlterTable
ALTER TABLE "Party" ADD COLUMN     "entryDeposit" INTEGER NOT NULL DEFAULT 2500,
ADD COLUMN     "entryFee" INTEGER NOT NULL DEFAULT 2000,
ADD COLUMN     "workDeposit" INTEGER NOT NULL DEFAULT 2500;
