# Default values for sommerlan.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/rouby/sommerlan-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

secrets:
  SESSION_SECRET: sommerlan-rocks-cookies
  APP_ORIGIN: "${APP_ORIGIN}"
  GOOGLE_SHEET_ID: "${GOOGLE_SHEET_ID}"
  GOOGLE_SERVICE_ACCOUNT_EMAIL: "${GOOGLE_SERVICE_ACCOUNT_EMAIL}"
  GOOGLE_PRIVATE_KEY: "${GOOGLE_PRIVATE_KEY}"
  NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
  NEW_RELIC_APP_NAME: "${NEW_RELIC_APP_NAME}"
  NEW_RELIC_LOADER_CONFIG: "${NEW_RELIC_LOADER_CONFIG}"
  NEW_RELIC_INFO: "${NEW_RELIC_INFO}"
  DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
  DISCORD_GUILD_ID: "${DISCORD_GUILD_ID}"
  DISCORD_ROLE_ID: "${DISCORD_ROLE_ID}"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    # ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: staging.sommerlan.rocks
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: sommerlan-tls
      hosts:
        - staging.sommerlan.rocks

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /live
    port: http
readinessProbe:
  httpGet:
    path: /ready
    port: http

volumes:
  - name: uploads
    persistentVolumeClaim:
      claimName: uploads

volumeMounts:
  - name: uploads
    mountPath: /myapp/dist/client/uploads

persistentVolumeClaims:
  - name: uploads
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
